name: Paint Contribution Graph

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Paint ASCII Art on Contribution Graph
        uses: qte77/gha-contribution-ascii@v2
        with:

          TEXT: "BRUTALLOLOL"

          START_DATE: "2024-08-04"
